version: "3"

services:
  path2back:
    image: openjdk
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgis/postgis
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: 1234