version: '3.7'
services:
  auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - mq
      - db
      - gateway
      - discovery
    environment:
      - 1=1

  user:
    build:
      context: ./ms-user
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - mq
      - db
      - gateway
      - discovery
    environment:
      - 1=1

  email:
    build:
      context: ./ms-email
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - mq
      - db
      - gateway
      - discovery
    environment:
      - 1=1
  mq:
    environment:
      - 1=1
  db:
    image: mysql
    environment:
      - MYSQL_PASSWORD=1234

  gateway:
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - discovery
    environment:
      - 1=1
    ports:
      - "8080:8080"

  discovery:
    build:
      context: ./ms-discovery
      dockerfile: Dockerfile
    networks:
      - app_net
    environment:
      - 1=1

  stop:
    build:
      context: ./ms-stop
      dockerfile: Dockerfile
    networks:
      - app_net
    depends_on:
      - mq
      - db
      - gateway
      - discovery
    environment:
      - 1=1

networks:
  - db_net:
  - app_net: