version: '3.7'
services:
  auth:
    image: openjdk
    environment:
      - 1=1
  user:
    image: openjdk
    environment:
      - 1=1
  email:
    image: openjdk
    environment:
      - 1=1
  mq:
    image: openjdk
    environment:
      - 1=1
  gateway:
    image: openjdk
    environment:
      - 1=1
  discovery:
    image: openjdk
    environment:
      - 1=1
