server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp:
      auth: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true