server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:xxxxxxxx}
    password: ${MAIL_PASSWORD:xxxxxxxx}
    smtp:
      auth: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  application:
    name: ms-email
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true