server:
  port: ${PORT:8081}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:path2}
    username: root
    password: 1234

  application:
    name: ms-auth
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: ${env.JWT_SECRET}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true