spring:
  application:
    name: ms-gateway
    ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1
          ## AUTH SERVICE
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka